// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package msgp_test

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *Item) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "ID":
			z.ID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "ID")
				return
			}
		case "N1":
			z.N1, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "N1")
				return
			}
		case "N2":
			z.N2, err = dc.ReadFloat64()
			if err != nil {
				err = msgp.WrapError(err, "N2")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z Item) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "ID"
	err = en.Append(0x83, 0xa2, 0x49, 0x44)
	if err != nil {
		return
	}
	err = en.WriteString(z.ID)
	if err != nil {
		err = msgp.WrapError(err, "ID")
		return
	}
	// write "N1"
	err = en.Append(0xa2, 0x4e, 0x31)
	if err != nil {
		return
	}
	err = en.WriteInt(z.N1)
	if err != nil {
		err = msgp.WrapError(err, "N1")
		return
	}
	// write "N2"
	err = en.Append(0xa2, 0x4e, 0x32)
	if err != nil {
		return
	}
	err = en.WriteFloat64(z.N2)
	if err != nil {
		err = msgp.WrapError(err, "N2")
		return
	}
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z Item) Msgsize() (s int) {
	s = 1 + 3 + msgp.StringPrefixSize + len(z.ID) + 3 + msgp.IntSize + 3 + msgp.Float64Size
	return
}
